### ISSUE TITLE
Where is the config file: srcn3d_v2-99_roi7_nusc_dd3d.py ?

### ISSUE THREAD

**Issue by afterthat97** [synsin0/SRCN3D#1]
Thank you for sharing your code!
Where is the config file: srcn3d_v2-99_roi7_nusc_dd3d.py?

**Comment by synsin0** [comment]
The v2-99 backbone config is now available in https://github.com/synsin0/SRCN3D/blob/main/projects/configs/srcn3d/srcn3d_v2-99_roi7_nusc_dd3d.py.

**Comment by afterthat97** [comment]
Thanks!
